"""Starter-file templates for ``incorporator init``.

Two scaffolds:

- ``stream`` → ``pipeline.json`` (single source ETL).
- ``fjord`` → ``pipeline.json`` + ``outflow.py`` (multi-source ETL with
  a user-defined ``outflow(state)`` join function).

Templates are hardcoded triple-quoted strings — no Jinja, no extra deps.
The CLI's ``init`` command writes them to disk and refuses to overwrite
existing files.

The JSON templates include ``//`` line comments above each key explaining
what to fill in. Because strict JSON disallows comments, the actual files
written use a leading ``_comment_`` key trick — readers ignore unknown
keys. Where developers add their own comments, they can either keep the
``_comment_`` keys or strip them; the validator ignores both.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict

STREAM_TEMPLATE_JSON = """{
  "_comment_1_": "Generated by 'incorporator init --type stream'.",
  "_comment_2_": "Edit, then: incorporator validate pipeline.json && incorporator stream pipeline.json",

  "incorp_params": {
    "_comment_": "Required. At least one of inc_url / inc_file / inc_parent / payload_list.",
    "_comment_auth_": "Auth headers can reference env vars: 'Bearer ${API_KEY}'.",
    "inc_url": "https://api.example.com/items",
    "inc_code": "id",
    "inc_name": "name",
    "headers": {
      "Accept": "application/json",
      "_example_auth_": "Bearer ${API_KEY}  -- copy under 'Authorization' to enable"
    }
  },

  "_comment_export_": "Optional. Path is relative to the CLI's working directory.",
  "_comment_export_2_": "Format is inferred from the extension (.csv, .ndjson, .parquet, ...).",
  "export_params": {
    "file_path": "data/items.csv"
  },

  "_comment_daemon_": "Set 'stateful_polling: true' + intervals for a long-lived daemon.",
  "stateful_polling": false,
  "refresh_interval": 60.0,
  "export_interval": 300.0
}
"""

FJORD_TEMPLATE_JSON = """{
  "_comment_1_": "Generated by 'incorporator init --type fjord'.",
  "_comment_2_": "Two sources are joined by the outflow(state) function in outflow.py.",
  "_comment_3_": "Optional 'inflow' sidecar can hold reusable helpers like calc() reducers.",

  "outflow": "outflow.py",

  "stream_params": [
    {
      "cls_name": "SourceA",
      "incorp_params": {
        "inc_url": "https://api.example.com/source_a",
        "inc_code": "id"
      },
      "refresh_params": {}
    },
    {
      "cls_name": "SourceB",
      "incorp_params": {
        "inc_url": "https://api.example.com/source_b",
        "inc_code": "id"
      },
      "refresh_params": {}
    }
  ],

  "export_params": {
    "file_path": "data/combined.ndjson"
  },

  "refresh_interval": 60.0,
  "export_interval": 300.0
}
"""

FJORD_TEMPLATE_PY = '''"""Outflow logic for the multi-source fjord pipeline.

Defines the two source ``Incorporator`` subclasses referenced from
``pipeline.json`` (``cls_name``) and the top-level ``outflow(state)``
function. The output class is **built dynamically** by ``fjord()`` from the
filename of this file (snake_case → PascalCase). For example, naming this
file ``coin_market.py`` would make the dynamic class ``CoinMarket``.
"""

from typing import Any, Dict, List

from incorporator import Incorporator


class SourceA(Incorporator):
    """Replace with your first source. Auto-inferred schema."""
    pass


class SourceB(Incorporator):
    """Replace with your second source. Auto-inferred schema."""
    pass


def outflow(state: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Combine the two source snapshots into the rows you want exported.

    ``state`` maps each ``cls_name`` from pipeline.json to that source's
    current ``IncorporatorList`` snapshot (a list of instances, with an
    ``inc_dict`` for O(1) primary-key lookup).

    Return a ``list[dict]`` — every key becomes a field on the dynamic
    output class. An empty return yields a zero-row wave and skips export.
    """
    rows: List[Dict[str, Any]] = []
    for a in state["SourceA"]:
        b = state["SourceB"].inc_dict.get(a.inc_code)
        if b is None:
            continue
        rows.append({
            "id": a.inc_code,
            # Add your derived fields here.
        })
    return rows
'''


INFLOW_TEMPLATE_PY = '''"""Custom DX helpers for your pipeline.json's incorp_params.

Any public name (no leading underscore) declared here is automatically
added to the CLI's token-resolver allow-list, so JSON tokens can
reference them by bare name.

Two ways to consume from pipeline.json:

  (1) bare-name reference via the @sigil — cleanest, no escapes::

        // inflow.py
        from incorporator.io.pagination import NextUrlPaginator
        from incorporator.schema.converters import inc, calc

        next_page = NextUrlPaginator("next")
        def _bst(rows): return sum(r.get("base_stat", 0) for r in rows)
        calc_bst = calc(_bst, "stats", default=0, target_type=int)

        // pipeline.json
        "inc_page":   "@next_page",
        "conv_dict":  {"stats": "@calc_bst"}

  (2) call-grammar — for one-offs that don't need a sidecar instance::

        "conv_dict": {"created_at": "inc(datetime)"}

Add reusable reducers, link_to factories, or per-source paginators
below — anything that the trinity's conv_dict / inc_page kwargs
need but JSON can't carry directly.
"""

from typing import Any, List


def calculate_bst(stats_array: List[dict]) -> int:
    """Example reducer: sum the 'base_stat' across a list of stat dicts.

    Replace with whatever your pipeline needs. Reference from
    pipeline.json with::

        "conv_dict": {"stats": "calc(calculate_bst, 'stats', default=0, target_type=int)"}
    """
    return sum(s.get("base_stat", 0) for s in stats_array if isinstance(s, dict))
'''


def files_for(scaffold_type: str, *, with_inflow: bool = False) -> Dict[str, str]:
    """Return a mapping of {filename: contents} for the requested scaffold.

    ``with_inflow`` adds an ``inflow.py`` template alongside the other
    files.  Defaults to ``False`` for ``--type stream`` (keep simple
    starts simple) and ``True`` for ``--type fjord`` (fjord pipelines
    almost always have user reducers).
    """
    if scaffold_type == "stream":
        files = {"pipeline.json": STREAM_TEMPLATE_JSON}
        if with_inflow:
            files["inflow.py"] = INFLOW_TEMPLATE_PY
        return files
    if scaffold_type == "fjord":
        files = {"pipeline.json": FJORD_TEMPLATE_JSON, "outflow.py": FJORD_TEMPLATE_PY}
        if with_inflow:
            files["inflow.py"] = INFLOW_TEMPLATE_PY
        return files
    raise ValueError(f"Unknown scaffold type: {scaffold_type!r}. Use 'stream' or 'fjord'.")


def write_scaffold(scaffold_type: str, output_dir: Path, *, with_inflow: bool = False) -> list[Path]:
    """Write the scaffold files into ``output_dir``.

    Returns the list of paths written. Raises FileExistsError if any target
    file already exists — never overwrites silently.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    files = files_for(scaffold_type, with_inflow=with_inflow)
    paths = [output_dir / name for name in files]
    existing = [p for p in paths if p.exists()]
    if existing:
        names = ", ".join(p.name for p in existing)
        raise FileExistsError(
            f"Refusing to overwrite existing file(s) in {output_dir}: {names}. "
            "Move them aside or choose a different --output-dir."
        )
    for name, content in files.items():
        (output_dir / name).write_text(content, encoding="utf-8")
    return paths
